version: '3'
services:
  whats-up-docker:
    image: fmartinou/whats-up-docker
    container_name: whats-up-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`wud.kdr.lan`)"
      - "tere=tereee"
    # t